### ISSUE TITLE
Failed to find valid time

### ISSUE THREAD

**Issue by arozhankov** [biddster/node-red-contrib-schedex#64] opened 2019-12-13 15:52 UTC
Hello!

I set the following settings: Friday, from 7 to 23 (see screenshot + code)
Now: Fri, 22:50
Node displays an error: "Failed to find valid time [07:00]"
<img width="199" alt="Снимок экрана 2019-12-13 в 22 50 47" src="https://user-images.githubusercontent.com/49441705/70812886-0ff60680-1dfb-11ea-921e-897985d2bb54.png">

Why?

==================
`[{"id":"77792c6e.3aa324","type":"schedex","z":"1da74fa3.e98a7","name":"DayTime_Fri 7-23","suspended":false,"lat":"55.018803","lon":"82.933952","ontime":"07:00","ontopic":"","onpayload":"","onoffset":0,"onrandomoffset":0,"offtime":"23:00","offtopic":"","offpayload":"","offoffset":0,"offrandomoffset":0,"mon":false,"tue":false,"wed":false,"thu":false,"fri":true,"sat":false,"sun":false,"x":330,"y":680,"wires":[["297c227f.07a79e"]]}]`

<img width="473" alt="Снимок экрана 2019-12-13 в 22 51 00" src="https://user-images.githubusercontent.com/49441705/70812907-1dab8c00-1dfb-11ea-94eb-3f0f61f553f5.png">

**Comment by tomSmartHome** [comment] 2019-12-16 09:50
I'm facing the same issue. It occurs when you set a time that has "already passed" as if it couldn't take the "next matching day of the week" for the schedule.

This makes me doubt that schedex supports recursive (weekly) scheduling, any experience here?

**Comment by arozhankov** [comment] 2019-12-16 10:19
> I'm facing the same issue. It occurs when you set a time that has "already passed" as if it couldn't take the "next matching day of the week" for the schedule.
> 
> This makes me doubt that schedex supports recursive (weekly) scheduling, any experience here?

Yes. About six months work fine for me.
I plan on the days of the week (different scenarios on different days of the week) the inclusion of lighting by motion sensors.

**Comment by tomSmartHome** [comment] 2019-12-16 12:53
I think it will still work correctly. 

My theory is that when a schedex node is initiated (you deployed changes, node red restarted, etc.) it fails when the only day of the week you picked is the current day of the week AND the time has already passed.

Instead I would expect that it takes the next matching day (in your case next Friday).

If you redeploy your flow on a different day than Friday (or on Friday before 7AM) it should be fine. 

This should still be fixed as unexpected reboots might impact "single day schedules".

**Comment by biddster** [comment] 2019-12-16 21:35
Sorry folks, this is a regression from a bit of refactoring I did to fix some other issues. Turns out I can't count!

I'll work up a unit test and try to fix it this week.

**Comment by biddster** [comment] 2019-12-20 20:37
Fixed in 1.7.1

**Closed by biddster** 2019-12-20 20:37 UTC
